/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Principal;

import java.awt.BorderLayout;
import javax.swing.JFrame;

/**
 *
 * @author Liliana
 */
public class Inicio extends javax.swing.JFrame
{

    ArregloDinamico arrU = new ArregloDinamico();
    

    /**
     * Creates new form Inicio
     */
    public Inicio()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        ubiF = new javax.swing.JLabel();
        ubiAt = new javax.swing.JLabel();
        invAt = new javax.swing.JLabel();
        invF = new javax.swing.JLabel();
        fondo = new javax.swing.JPanel();
        tit = new javax.swing.JLabel();
        tit2 = new javax.swing.JLabel();
        iniSes = new javax.swing.JLabel();
        reg = new javax.swing.JLabel();
        menu = new javax.swing.JLabel();
        inventario = new javax.swing.JLabel();
        ubicacion = new javax.swing.JLabel();
        bgInSes = new javax.swing.JPanel();

        ubiF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Lugar.png"))); // NOI18N

        ubiAt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/UbiAt.png"))); // NOI18N

        invAt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/InventarioA.png"))); // NOI18N

        invF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Inventario.png"))); // NOI18N
        invF.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                invFMouseEntered(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PHARMACY PLUS");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt)
            {
                formWindowOpened(evt);
            }
        });

        fondo.setBackground(new java.awt.Color(0, 140, 188));
        fondo.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                fondoMouseEntered(evt);
            }
        });

        tit.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 36)); // NOI18N
        tit.setForeground(new java.awt.Color(255, 255, 255));
        tit.setText("PHARMACY");

        tit2.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 36)); // NOI18N
        tit2.setForeground(new java.awt.Color(255, 255, 255));
        tit2.setText("PLUS");

        iniSes.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 18)); // NOI18N
        iniSes.setForeground(new java.awt.Color(255, 255, 255));
        iniSes.setText("Iniciar Sesión");
        iniSes.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                iniSesMouseClicked(evt);
            }
        });

        reg.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 18)); // NOI18N
        reg.setForeground(new java.awt.Color(255, 255, 255));
        reg.setText("Registrarse");
        reg.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                regMouseClicked(evt);
            }
        });

        menu.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        menu.setForeground(new java.awt.Color(255, 255, 255));
        menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/menu.png"))); // NOI18N

        inventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Inventario.png"))); // NOI18N
        inventario.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                inventarioMouseEntered(evt);
            }
        });

        ubicacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Lugar.png"))); // NOI18N
        ubicacion.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                ubicacionMouseEntered(evt);
            }
        });

        bgInSes.setBackground(new java.awt.Color(0, 140, 188));
        bgInSes.setPreferredSize(new java.awt.Dimension(296, 320));

        javax.swing.GroupLayout bgInSesLayout = new javax.swing.GroupLayout(bgInSes);
        bgInSes.setLayout(bgInSesLayout);
        bgInSesLayout.setHorizontalGroup(
            bgInSesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 296, Short.MAX_VALUE)
        );
        bgInSesLayout.setVerticalGroup(
            bgInSesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout fondoLayout = new javax.swing.GroupLayout(fondo);
        fondo.setLayout(fondoLayout);
        fondoLayout.setHorizontalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoLayout.createSequentialGroup()
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(fondoLayout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(tit))
                            .addComponent(tit2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 435, Short.MAX_VALUE))
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ubicacion)
                        .addGap(65, 65, 65)
                        .addComponent(inventario)
                        .addGap(58, 58, 58)))
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bgInSes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addComponent(iniSes)
                        .addGap(18, 18, 18)
                        .addComponent(reg)
                        .addGap(13, 13, 13)
                        .addComponent(menu)))
                .addGap(42, 42, 42))
        );
        fondoLayout.setVerticalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(tit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tit2)
                    .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(fondoLayout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(iniSes)
                                .addComponent(reg)))
                        .addComponent(menu)))
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ubicacion)
                            .addComponent(inventario)))
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(bgInSes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(134, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void iniSesMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_iniSesMouseClicked
    {//GEN-HEADEREND:event_iniSesMouseClicked
        InSes is = new InSes(arrU, fondo);
        is.setSize(296, 320);
        is.setLocation(0, 0);
        bgInSes.removeAll();
        bgInSes.add(is, BorderLayout.CENTER);
        bgInSes.revalidate();
        bgInSes.repaint();
        // TODO add your handling code here:
    }//GEN-LAST:event_iniSesMouseClicked

    private void regMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_regMouseClicked
    {//GEN-HEADEREND:event_regMouseClicked
        Reg reg = new Reg(arrU);
        reg.setSize(296, 320);
        reg.setLocation(0, 0);
        bgInSes.removeAll();
        bgInSes.add(reg, BorderLayout.CENTER);
        bgInSes.revalidate();
        bgInSes.repaint();
        // TODO add your handling code here:
    }//GEN-LAST:event_regMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowOpened
    {//GEN-HEADEREND:event_formWindowOpened
        
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosing(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosing
    {//GEN-HEADEREND:event_formWindowClosing
        
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void ubicacionMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_ubicacionMouseEntered
    {//GEN-HEADEREND:event_ubicacionMouseEntered
        // TODO add your handling code here:
        ubicacion.setIcon(ubiAt.getIcon());
    }//GEN-LAST:event_ubicacionMouseEntered

    private void fondoMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_fondoMouseEntered
    {//GEN-HEADEREND:event_fondoMouseEntered
        // TODO add your handling code here:
        ubicacion.setIcon(ubiF.getIcon());
        inventario.setIcon(invF.getIcon());
    }//GEN-LAST:event_fondoMouseEntered

    private void inventarioMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_inventarioMouseEntered
    {//GEN-HEADEREND:event_inventarioMouseEntered
        // TODO add your handling code here:
        inventario.setIcon(invAt.getIcon());
    }//GEN-LAST:event_inventarioMouseEntered

    private void invFMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_invFMouseEntered
    {//GEN-HEADEREND:event_invFMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_invFMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new Inicio().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgInSes;
    private javax.swing.JPanel fondo;
    private javax.swing.JLabel iniSes;
    private javax.swing.JLabel invAt;
    private javax.swing.JLabel invF;
    private javax.swing.JLabel inventario;
    private javax.swing.JLabel menu;
    private javax.swing.JLabel reg;
    private javax.swing.JLabel tit;
    private javax.swing.JLabel tit2;
    private javax.swing.JLabel ubiAt;
    private javax.swing.JLabel ubiF;
    private javax.swing.JLabel ubicacion;
    // End of variables declaration//GEN-END:variables
}
