/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Principal;

import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Liliana
 */
public class MenuAdmin extends javax.swing.JPanel
{
    MenuP mp = new MenuP();
    Multilistas multiLS = new Multilistas();

    /**
     * Creates new form MenuAdmin
     */
    public MenuAdmin(MenuP m, Multilistas ms)
    {
        initComponents();
        mp = m;
        multiLS = ms;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        fondoOpc = new javax.swing.JPanel();
        altas = new javax.swing.JLabel();
        bajas = new javax.swing.JLabel();
        consultas = new javax.swing.JLabel();
        mover = new javax.swing.JLabel();
        salir = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(105, 600));

        fondoOpc.setBackground(new java.awt.Color(0, 140, 188));
        fondoOpc.setPreferredSize(new java.awt.Dimension(105, 600));
        fondoOpc.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                fondoOpcMouseClicked(evt);
            }
        });

        altas.setForeground(java.awt.Color.lightGray);
        altas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        altas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Alta.png"))); // NOI18N
        altas.setToolTipText("Altas");
        altas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        altas.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                altasMouseClicked(evt);
            }
        });

        bajas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bajas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Baja.png"))); // NOI18N
        bajas.setToolTipText("Bajas");
        bajas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bajas.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                bajasMouseClicked(evt);
            }
        });

        consultas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        consultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Consultas.png"))); // NOI18N
        consultas.setToolTipText("Consultas");
        consultas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        mover.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Mover.png"))); // NOI18N
        mover.setToolTipText("Mover Productos");
        mover.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        salir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Salir.png"))); // NOI18N
        salir.setToolTipText("Salir de la Cuenta");
        salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salir.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                salirMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout fondoOpcLayout = new javax.swing.GroupLayout(fondoOpc);
        fondoOpc.setLayout(fondoOpcLayout);
        fondoOpcLayout.setHorizontalGroup(
            fondoOpcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(altas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
            .addComponent(bajas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(consultas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mover, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(salir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        fondoOpcLayout.setVerticalGroup(
            fondoOpcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoOpcLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(altas)
                .addGap(34, 34, 34)
                .addComponent(bajas)
                .addGap(50, 50, 50)
                .addComponent(consultas)
                .addGap(32, 32, 32)
                .addComponent(mover)
                .addGap(32, 32, 32)
                .addComponent(salir)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(fondoOpc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoOpc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void altasMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_altasMouseClicked
    {//GEN-HEADEREND:event_altasMouseClicked
        // TODO add your handling code here:
        MenuAltas ma = new MenuAltas(mp, MenuAdmin.this, multiLS);
        ma.setSize(308, 374);
        ma.setLocation(0, 0);
        mp.getFondoAB().removeAll();
        mp.getFondoAB().add(ma, BorderLayout.CENTER);
        mp.getFondoAB().revalidate();
        mp.getFondoAB().repaint();
    }//GEN-LAST:event_altasMouseClicked

    private void bajasMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_bajasMouseClicked
    {//GEN-HEADEREND:event_bajasMouseClicked
        // TODO add your handling code here:
        MenuBajas ma = new MenuBajas(mp, MenuAdmin.this);
        ma.setSize(308, 374);
        ma.setLocation(0, 129);
        mp.getFondoAB().removeAll();
        mp.getFondoAB().add(ma, BorderLayout.CENTER);
        mp.getFondoAB().revalidate();
        mp.getFondoAB().repaint();
    }//GEN-LAST:event_bajasMouseClicked

    private void fondoOpcMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_fondoOpcMouseClicked
    {//GEN-HEADEREND:event_fondoOpcMouseClicked
        // TODO add your handling code here:
        mp.getFondoAB().removeAll();
        mp.getFondoAB().revalidate();
        mp.getFondoAB().repaint();
    }//GEN-LAST:event_fondoOpcMouseClicked

    private void salirMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_salirMouseClicked
    {//GEN-HEADEREND:event_salirMouseClicked
        // TODO add your handling code here:
        Inicio in = new Inicio();
        in.getFondo().setSize(1080, 600);
        in.getFondo().setLocation(0, 0);
        mp.getFondo().removeAll();
        mp.getFondo().add(in.getFondo());
        mp.getFondo().revalidate();
        mp.getFondo().repaint();
    }//GEN-LAST:event_salirMouseClicked

    public MenuP getMp()
    {
        return mp;
    }

    public void setMp(MenuP mp)
    {
        this.mp = mp;
    }

    public JLabel getAltas()
    {
        return altas;
    }

    public void setAltas(JLabel altas)
    {
        this.altas = altas;
    }

    public JLabel getBajas()
    {
        return bajas;
    }

    public void setBajas(JLabel bajas)
    {
        this.bajas = bajas;
    }

    public JLabel getConsultas()
    {
        return consultas;
    }

    public void setConsultas(JLabel consultas)
    {
        this.consultas = consultas;
    }

    public JPanel getFondoOpc()
    {
        return fondoOpc;
    }

    public void setFondoOpc(JPanel fondoOpc)
    {
        this.fondoOpc = fondoOpc;
    }

    public JLabel getMover()
    {
        return mover;
    }

    public void setMover(JLabel mover)
    {
        this.mover = mover;
    }

    public JLabel getSalir()
    {
        return salir;
    }

    public void setSalir(JLabel salir)
    {
        this.salir = salir;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel altas;
    private javax.swing.JLabel bajas;
    private javax.swing.JLabel consultas;
    private javax.swing.JPanel fondoOpc;
    private javax.swing.JLabel mover;
    private javax.swing.JLabel salir;
    // End of variables declaration//GEN-END:variables
}
