/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Principal;

import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 *
 * @author Liliana
 */
public class MenuP extends javax.swing.JPanel
{

    /**
     * Creates new form MenuP
     */
    public MenuP()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        fondo = new javax.swing.JPanel();
        fondoAB = new javax.swing.JPanel();
        fondoOpc = new javax.swing.JPanel();

        setBackground(new java.awt.Color(220, 220, 220));
        setVerifyInputWhenFocusTarget(false);

        fondo.setBackground(new java.awt.Color(220, 220, 220));
        fondo.setToolTipText("Altas");

        fondoAB.setBackground(new java.awt.Color(220, 220, 220));

        javax.swing.GroupLayout fondoABLayout = new javax.swing.GroupLayout(fondoAB);
        fondoAB.setLayout(fondoABLayout);
        fondoABLayout.setHorizontalGroup(
            fondoABLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 556, Short.MAX_VALUE)
        );
        fondoABLayout.setVerticalGroup(
            fondoABLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 374, Short.MAX_VALUE)
        );

        fondoOpc.setBackground(new java.awt.Color(0, 140, 188));

        javax.swing.GroupLayout fondoOpcLayout = new javax.swing.GroupLayout(fondoOpc);
        fondoOpc.setLayout(fondoOpcLayout);
        fondoOpcLayout.setHorizontalGroup(
            fondoOpcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 105, Short.MAX_VALUE)
        );
        fondoOpcLayout.setVerticalGroup(
            fondoOpcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout fondoLayout = new javax.swing.GroupLayout(fondo);
        fondo.setLayout(fondoLayout);
        fondoLayout.setHorizontalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addComponent(fondoOpc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(fondoAB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 363, Short.MAX_VALUE))
        );
        fondoLayout.setVerticalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoOpc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(fondoLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(fondoAB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel fondo;
    private javax.swing.JPanel fondoAB;
    private javax.swing.JPanel fondoOpc;
    // End of variables declaration//GEN-END:variables

    public JPanel getFondoOpc()
    {
        return fondoOpc;
    }

    public void setFondoOpc(JPanel fondoOpc)
    {
        this.fondoOpc = fondoOpc;
    }

    public JPanel getFondoAB()
    {
        return fondoAB;
    }

    public void setFondoAB(JPanel fondoAB)
    {
        this.fondoAB = fondoAB;
    }

    public JPanel getFondo()
    {
        return fondo;
    }

    public void setFondo(JPanel fondo)
    {
        this.fondo = fondo;
    }
    
}
