/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Principal;

/**
 *
 * @author Liliana
 */
public class MenuUser extends javax.swing.JPanel
{

    /**
     * Creates new form MenuAdmin
     */
    public MenuUser()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        fondoOpc = new javax.swing.JPanel();
        altas = new javax.swing.JLabel();
        bajas = new javax.swing.JLabel();
        consultas = new javax.swing.JLabel();
        mover = new javax.swing.JLabel();
        salir = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(105, 600));

        fondoOpc.setBackground(new java.awt.Color(0, 140, 188));
        fondoOpc.setPreferredSize(new java.awt.Dimension(105, 600));

        altas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Alta.png"))); // NOI18N
        altas.setToolTipText("Altas");
        altas.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                altasMouseClicked(evt);
            }
        });

        bajas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Baja.png"))); // NOI18N
        bajas.setToolTipText("Bajas");

        consultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Consultas.png"))); // NOI18N
        consultas.setToolTipText("Consultas");

        mover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Mover.png"))); // NOI18N
        mover.setToolTipText("Mover Productos");

        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Salir.png"))); // NOI18N
        salir.setToolTipText("Salir de la Cuenta");

        javax.swing.GroupLayout fondoOpcLayout = new javax.swing.GroupLayout(fondoOpc);
        fondoOpc.setLayout(fondoOpcLayout);
        fondoOpcLayout.setHorizontalGroup(
            fondoOpcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoOpcLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(fondoOpcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(consultas)
                    .addComponent(bajas)
                    .addComponent(altas))
                .addGap(20, 20, 20))
            .addGroup(fondoOpcLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fondoOpcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mover)
                    .addComponent(salir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        fondoOpcLayout.setVerticalGroup(
            fondoOpcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoOpcLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(altas)
                .addGap(42, 42, 42)
                .addComponent(bajas)
                .addGap(42, 42, 42)
                .addComponent(consultas)
                .addGap(42, 42, 42)
                .addComponent(mover)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(salir)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(fondoOpc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoOpc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void altasMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_altasMouseClicked
    {//GEN-HEADEREND:event_altasMouseClicked
        // TODO add your handling code here:
        MenuP mp = new MenuP();
        mp.getFondoAB().removeAll();
    }//GEN-LAST:event_altasMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel altas;
    private javax.swing.JLabel bajas;
    private javax.swing.JLabel consultas;
    private javax.swing.JPanel fondoOpc;
    private javax.swing.JLabel mover;
    private javax.swing.JLabel salir;
    // End of variables declaration//GEN-END:variables
}
